version: "3.8"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true" # Enables hot reload within docker
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules/ # Excludes local node modules

  db:
    image: "postgres"
    container_name: db
    ports:
      - 9000:5432
    environment:
      - POSTGRES_PASSWORD=gitlab-analyzer
      - POSTGRES_USER=gitlab-analyzer

# Code below will persist data even when container shuts off
# Commented out for now because the db will be constantly changing as we figure out how to structure our app
#     volumes:
#       - database-data:/var/lib/postgresql/data/ 
# volumes:
#   database-data: